### ISSUE TITLE
不跳转其他Activity选择图片

### ISSUE THREAD

**Issue by JavaBoyHW** [NFLeo/Matisse#1]
库很好，但我现在有个需求，好像无法实现。
我想在一个Fragment中，上半部分显示选择好的图片，下半部分显示选择图片的列表。
这个库在选择图片时是跳转到一个Activity中选择并返回，能不能不跳转，直接在一个页面的一部分上显示。

**Comment by NFLeo** [comment]
也可以的啊，数据源的获取知乎已经帮我们写好了，我看你的需求也不难，改下界面填充一下数据就可以了，大方向不需要怎么改

**Comment by JavaBoyHW** [comment]
@NFLeo 。我对Matisse研究不多。给提供个详细点的思路嘛？

**Comment by NFLeo** [comment]
Matisse UI方面的代码都不难，就是在那几个activity里操作的，根据你的布局需求，修改xml文件。如果你说你想在Fragment容器里面操作，那改动的东西很多，没法讲的清楚额。
