### ISSUE TITLE
裁剪后没有返回Uri

### ISSUE THREAD

**Issue by lijianqiang12** [NFLeo/Matisse#2]
private void returnCropData(String cropPath) {
    Intent result = new Intent();
    ArrayList<Uri> selectedUris = new ArrayList<>();
    ArrayList<String> selectedPaths = new ArrayList<>();
    selectedUris.add(Uri.parse(cropPath));//之前只添加了path，没添加uri
    selectedPaths.add(cropPath);
    result.putParcelableArrayListExtra(EXTRA_RESULT_SELECTION, selectedUris);
    result.putStringArrayListExtra(EXTRA_RESULT_SELECTION_PATH, selectedPaths);
    setResult(RESULT_OK, result);
    finish();
  }

**Comment by NFLeo** [comment]
额，是的，因为我只需要一个path，所以没返回uri，这个拿到path以后也可以转一下的。毕竟一个值传了好多次，多个值的话传递太麻烦，一直考虑不用这个传值方式，但是改动的话对Matisse原库的修改就太大了，一直没去改

**Comment by lijianqiang12** [comment]
嗯嗯，刚开始我也只是按照知乎官方的文档写得，一直获取不到Uri，然后就是一顿查，建议在Readme里说明一下，既然留了接口，返回空值总感觉有点。。。

**Comment by NFLeo** [comment]
嗯，好的，那我标注一下
