### ISSUE TITLE
cropWidth和cropHeight设置

### ISSUE THREAD

**Issue by lijianqiang12** [NFLeo/Matisse#3]
//    int cropWidth = mSpec.cropFocusWidth > 0 && mSpec.cropFocusWidth < UIUtils.getScreenWidth(this) - (int) SizeUtils.dp2px(this, 50)
//            ? mSpec.cropFocusWidth : UIUtils.getScreenWidth(this) - (int) SizeUtils.dp2px(this, 50);
//
//    int cropHeight = mSpec.cropFocusHeight > 0 && mSpec.cropFocusHeight < UIUtils.getScreenHeight(this) - (int) SizeUtils.dp2px(this, 400)
//            ? mSpec.cropFocusHeight : UIUtils.getScreenHeight(this) - (int) SizeUtils.dp2px(this, 400);

如果crop和output设置的长宽比例不同的话，图片会变形，而且400设置感觉有点多了。。。
不过还是感谢，裁剪功能非常有用，终于把丑爆的ImagePicker替换掉了= =

**Comment by NFLeo** [comment]
只是把几个比较好的库整合了一下而已，，裁剪尺寸也是暴露出来属性控制，裁剪默认值得话，当时简单做了一下限制，
