### ISSUE TITLE
这个框架怎么用？下载之后settings.gradle中引用么？

### ISSUE THREAD

**Issue by jingchangfa** [NFLeo/Matisse#4]
include ':app', ':matisse'
之后找不到路径是为什么呢

**Comment by jingchangfa** [comment]
compile project(path: ':matisse')
ok了 不好意思 有点生疏

**Comment by NFLeo** [comment]
嗯呐   能用就好  代码有点乱最近都没怎么改了  等这段日子过完了准备用kotlin重构一下，到时候还会添加网络依赖，那样就没现在这么麻烦了
