### ISSUE TITLE
android studio如何添加依赖包

### ISSUE THREAD

**Issue by xiangzi9626** [NFLeo/Matisse#5]
android studio 中如何把matisse包添加进来，

**Comment by NFLeo** [comment]
建议使用https://github.com/NFLeo/Matisse-Kotlin这个哈，java、kotlin项目通用，具体使用按照说明来就好了，这个库不维护了

使用这个库需要
1.把matisse拷到项目依赖这个lib
2.androidmanifast注册文件读写权限、provider
3.获取权限后按项目里说明调用就好了
