### ISSUE TITLE
不能选择mp4

### ISSUE THREAD

**Issue by EthanReedLabs** [NFLeo/Matisse#7]
按照提示，找到 MimeType 这个文件，里面和 Androidx 版本的是一致的，尝试导入 aar 包后，项目有部分第三方库暂时不能使用 Androidx，我将代码迁移到项目中，尝试本地更改。

**Comment by NFLeo** [comment]
master分支已经改了，这个分支不是用androidx的，里面的aar可以拿来用。上传不到jcenter，所以只能打aar了

**Comment by NFLeo** [comment]
回复错了  我说的是那个Matisse-Kotlin库
